name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          az acr login --name resumeanalyzerpranav

      - name: Build and Push Image
        run: |
          docker build -t resumeanalyzerpranav.azurecr.io/resume-analyzer:latest .
          docker push resumeanalyzerpranav.azurecr.io/resume-analyzer:latest

      - name: Deploy to Container App
        run: |
          az extension add --name containerapp --upgrade
          az containerapp create \
            --name resume-analyzer \
            --resource-group resume-rg-india \
            --environment resume-env \
            --image resumeanalyzerpranav.azurecr.io/resume-analyzer:latest \
            --target-port 8000 \
            --ingress external \
            --registry-server resumeanalyzerpranav.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --query properties.configuration.ingress.fqdn
